name: Caching

on: [push , workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Cache
      id: cache
      uses: actions/cache@v3
      with:
        path: README.md
        key: key-test

    - run: echo ${{ steps.cache.outputs.cache-hit }}
    
